#!/bin/bash

####################################
# run this script to begin the project
#
# NOTE:  always run me as: "./run"
####################################

if [ $# -eq 0 ] || ( [ $# -eq 1 ] && [ $1 -eq 3 ] ); then
    python3 -B -m pyz.main
fi

if [ $# -eq 1 ] && [ $1 -eq 2 ]; then
    python2 -B -m pyz.main
fi
